### ISSUE TITLE
search for winpty-agent.exe in PATH

### ISSUE THREAD

**Issue by prabirshrestha** [zacps/alacritty#16]
Which operating system does the issue occur on?
Win10

I use winpty for other command line tools and `winpty-agent.exe` is already in the path environment variable. Would be good to load it from there if it doesn't find it with alacritty.exe

**Comment by zacps** [comment]
Interesting. This is actually an issue in the [winpty](https://github.com/rprichard/winpty) project rather than alacritty.
The relevant code is the `findAgentProgram` function in `winpty/src/libwinpty/AgentLocation.cc:66` which just looks in the client's directory.
Closing as it's not controllable from alacritty, consider creating an issue there.
